server:
  port: 9084

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/booking_db
    username: postgres
    password: postgres

  application:
    name: booking-service

jwt:
  secret: mysupersecuresecretkeythatisatleast32characterslong123

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:9761/eureka/}
