server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    active: dev

  logging:
    file:
      name: logs/log.txt

  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:configserver:http://config-server:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

jwt:
  secret: mysupersecuresecretkeythatisatleast32characterslong123
